[env:esp32dev]
; Plataforma, placa y framework usados para compilar el firmware.
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Librerias para pantalla, JSON meteorologico y decodificacion de iconos PNG.
lib_deps =
  bodmer/TFT_eSPI@^2.5.43
  bblanchon/ArduinoJson@^7.2.1
  bitbank2/PNGdec@^1.1.2

; Convierte los PNG en datos binarios enlazados dentro de firmware.bin.
board_build.embed_files =
  src/images/icons/icons8-cloud-48.png
  src/images/icons/icons8-night-48.png
  src/images/icons/icons8-partly-cloudy-day-48.png
  src/images/icons/icons8-snow-48.png
  src/images/icons/icons8-snow-storm-48.png
  src/images/icons/icons8-snowy-sunny-day-48.png
  src/images/icons/icons8-storm-48.png
  src/images/icons/icons8-sun-48.png
  src/images/icons/icons8-umbrella-48.png
  src/images/icons/icons8-windy-weather-48.png

; Configuracion de TFT_eSPI sin modificar User_Setup.h dentro de la libreria.
build_flags =
  -D USER_SETUP_LOADED=1
  -D GC9A01_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=240
  -D TFT_MOSI=23
  -D TFT_SCLK=18
  -D TFT_CS=5
  -D TFT_DC=16
  -D TFT_RST=4
  -D TFT_BL=17
  -D LOAD_GFXFF=1
  ; Frecuencias de escritura y lectura del bus SPI.
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=20000000
