[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library@^1.11.11
  adafruit/Adafruit GC9A01A@^1.1.0
  bblanchon/ArduinoJson@^7.2.1
build_flags =
  -D TFT_MOSI=23
  -D TFT_SCLK=18
  -D TFT_CS=5
  -D TFT_DC=16
  -D TFT_RST=4
  -D TFT_BL=17
